### PR TITLE
Trialoge: Fix npc visual swap in G1

### PR DESCRIPTION
**Pull request by CarnageMarkus**
Teeth texture wasn't set properly... Caused visual bugs

### CODE REVIEW

**Review by szapp — COMMENTED** [review]
Looks good! Have you tested the changes with Gothic 2 as well?

**Comment by CarnageMarkus** [comment]
No, but I am sure nothing changed in this external between G1 and G2.
It's basically doing  x = x; (then doing some internal visual reload). Previous implementation did reset skin color and teeth variation to 0, which was wrong in the first place. 
This went unnoticed as G2 did not use skin colors that much as well as teeth textures compared to G1.

If you insist, I can do some test.

**Comment by szapp** [comment]
Yes, that's what I meant:
- Can (the external in) G2 handle a non-zero teeth texture? (Testing by simply running this function in G2)
- Does the constants `oCNpc_bitfield2_teeth_TexVarNr` exist in the class definitions of Ikarus for G2?

If you don't have G2 installed to test it, let me know.


Aside from that, it seems you have introduced a lot of white space changes in ` Trialoge.d`, when performing the merge (your second commit 3613677). In case you can revert this, it would make tracking the changes easier in the future.

**Comment by CarnageMarkus** [comment]
To both questions yes. I used varied teeth textures (which included eye textures) in my personal projects many times.

Other changes are not whitespace, but rather to me unknown change in "German Umlaute". I use VS Code editor with Windows 1252 encoding for .d files. What type of encoding is used on those scripts originally ?

**Comment by szapp** [comment]
Thanks!

**Pull request merged**
